dotnet ef database drop --project src/Modules/Core/Lister.Core.Infrastructure.Sql/Lister.Core.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Core.Infrastructure.Sql.DataProtectionKeyDbContext --configuration Debug --verbose --force

dotnet ef migrations remove --project src/Modules/Lists/Lister.Lists.Infrastructure.Sql/Lister.Lists.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Lists.Infrastructure.Sql.ListsDbContext --configuration Debug --verbose --force
dotnet ef migrations add --project src/Modules/Lists/Lister.Lists.Infrastructure.Sql/Lister.Lists.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Lists.Infrastructure.Sql.ListsDbContext --configuration Debug --verbose Initial --output-dir Migrations

dotnet ef migrations remove --project src/Modules/Users/Lister.Users.Infrastructure.Sql/Lister.Users.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Users.Infrastructure.Sql.UsersDbContext --configuration Debug --verbose --force
dotnet ef migrations add --project src/Modules/Users/Lister.Users.Infrastructure.Sql/Lister.Users.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Users.Infrastructure.Sql.UsersDbContext --configuration Debug --verbose Initial --output-dir Migrations

dotnet ef migrations remove --project src/Modules/Core/Lister.Core.Infrastructure.Sql/Lister.Core.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Core.Infrastructure.Sql.DataProtectionKeyDbContext --configuration Debug --verbose --force
dotnet ef migrations add --project src/Modules/Core/Lister.Core.Infrastructure.Sql/Lister.Core.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Core.Infrastructure.Sql.DataProtectionKeyDbContext --configuration Debug --verbose Initial --output-dir Migrations

dotnet ef migrations remove --project src/Modules/Notifications/Lister.Notifications.Infrastructure.Sql/Lister.Notifications.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Notifications.Infrastructure.Sql.NotificationsDbContext --configuration Debug --verbose --force
dotnet ef migrations add --project src/Modules/Notifications/Lister.Notifications.Infrastructure.Sql/Lister.Notifications.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Notifications.Infrastructure.Sql.NotificationsDbContext --configuration Debug --verbose Initial --output-dir Migrations

dotnet ef database update --project src/Modules/Lists/Lister.Lists.Infrastructure.Sql/Lister.Lists.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Lists.Infrastructure.Sql.ListsDbContext --configuration Debug --verbose
dotnet ef database update --project src/Modules/Users/Lister.Users.Infrastructure.Sql/Lister.Users.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Users.Infrastructure.Sql.UsersDbContext --configuration Debug --verbose
dotnet ef database update --project src/Modules/Core/Lister.Core.Infrastructure.Sql/Lister.Core.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Core.Infrastructure.Sql.DataProtectionKeyDbContext --configuration Debug --verbose
dotnet ef database update --project src/Modules/Notifications/Lister.Notifications.Infrastructure.Sql/Lister.Notifications.Infrastructure.Sql.csproj --startup-project src/Lister.App.Server/Lister.App.Server.csproj --context Lister.Notifications.Infrastructure.Sql.NotificationsDbContext --configuration Debug --verbose